# Geoapify API Configuration
# https://apidocs.geoapify.com/docs/places/

Rails.application.config.geoapify = ActiveSupport::OrderedOptions.new
Rails.application.config.geoapify.api_key = ENV.fetch("GEOAPIFY_API_KEY", nil)
Rails.application.config.geoapify.base_url = "https://api.geoapify.com/v2"

# Default search radius in meters (10km)
Rails.application.config.geoapify.default_radius = 10_000

# Maximum results per request (Geoapify allows up to 500)
Rails.application.config.geoapify.max_results = 100

# Supported place categories for tourism experiences
# https://apidocs.geoapify.com/docs/places/#categories
# Complete list of all Geoapify categories
Rails.application.config.geoapify.tourism_categories = %w[
  accommodation
  accommodation.hotel
  accommodation.hut
  accommodation.apartment
  accommodation.chalet
  accommodation.guest_house
  accommodation.hostel
  accommodation.motel

  camping
  camping.camp_pitch
  camping.camp_site
  camping.summer_camp
  camping.caravan_site

  activity
  activity.community_center
  activity.sport_club

  building
  building.accommodation
  building.commercial
  building.historic
  building.industrial
  building.office
  building.public
  building.residential
  building.tourism

  catering
  catering.restaurant
  catering.restaurant.pizza
  catering.restaurant.burger
  catering.restaurant.regional
  catering.restaurant.italian
  catering.restaurant.chinese
  catering.restaurant.japanese
  catering.restaurant.indian
  catering.restaurant.thai
  catering.restaurant.mexican
  catering.restaurant.kebab
  catering.restaurant.noodle
  catering.restaurant.seafood
  catering.restaurant.steak_house
  catering.restaurant.sushi
  catering.restaurant.fish_and_chips
  catering.restaurant.fish
  catering.restaurant.ramen
  catering.restaurant.chicken
  catering.restaurant.vietnamese
  catering.restaurant.korean
  catering.restaurant.greek
  catering.restaurant.french
  catering.restaurant.spanish
  catering.restaurant.turkish
  catering.restaurant.american
  catering.cafe
  catering.cafe.coffee_shop
  catering.cafe.coffee
  catering.cafe.tea
  catering.fast_food
  catering.fast_food.pizza
  catering.fast_food.burger
  catering.fast_food.sandwich
  catering.fast_food.kebab
  catering.fast_food.fish_and_chips
  catering.fast_food.chicken
  catering.fast_food.ice_cream
  catering.bar
  catering.bar.wine
  catering.bar.cocktail
  catering.bar.beer
  catering.bar.sports
  catering.pub
  catering.biergarten
  catering.taproom
  catering.winery
  catering.food_court
  catering.ice_cream

  commercial
  commercial.supermarket
  commercial.marketplace
  commercial.shopping_mall
  commercial.department_store
  commercial.clothing
  commercial.clothing.shoes
  commercial.clothing.underwear
  commercial.clothing.sport
  commercial.clothing.men
  commercial.clothing.women
  commercial.clothing.kids
  commercial.clothing.brand
  commercial.clothing.second_hand
  commercial.bag
  commercial.jewelry
  commercial.jewelry.watches
  commercial.books
  commercial.gift
  commercial.stationery
  commercial.newsagent
  commercial.ticket
  commercial.antiques
  commercial.art
  commercial.outdoor_and_sport
  commercial.outdoor_and_sport.water_sports
  commercial.outdoor_and_sport.ski
  commercial.outdoor_and_sport.bicycle
  commercial.outdoor_and_sport.hunting
  commercial.outdoor_and_sport.fishing
  commercial.outdoor_and_sport.golf
  commercial.hobby
  commercial.hobby.art
  commercial.hobby.music
  commercial.hobby.games
  commercial.hobby.video_games
  commercial.hobby.craft
  commercial.hobby.model
  commercial.hobby.collecting
  commercial.hobby.sewing
  commercial.hobby.anime
  commercial.hobby.photo
  commercial.hobby.trophy
  commercial.music
  commercial.musical_instrument
  commercial.video
  commercial.electronics
  commercial.electronics.computer
  commercial.electronics.hifi
  commercial.electronics.mobile_phone
  commercial.electronics.communication
  commercial.electronics.photo
  commercial.electronics.robot
  commercial.electronics.radiotechnics
  commercial.electronics.vacuum_cleaner
  commercial.hardware
  commercial.garden
  commercial.florist
  commercial.food_and_drink
  commercial.food_and_drink.bakery
  commercial.food_and_drink.deli
  commercial.food_and_drink.butcher
  commercial.food_and_drink.wine
  commercial.food_and_drink.beverages
  commercial.food_and_drink.greengrocer
  commercial.food_and_drink.farm
  commercial.food_and_drink.honey
  commercial.food_and_drink.health_food
  commercial.food_and_drink.frozen_food
  commercial.food_and_drink.seafood
  commercial.food_and_drink.cheese
  commercial.food_and_drink.chocolate
  commercial.food_and_drink.coffee
  commercial.food_and_drink.tea
  commercial.food_and_drink.spices
  commercial.food_and_drink.confectionery
  commercial.food_and_drink.pasta
  commercial.convenience
  commercial.discount_store
  commercial.kiosk
  commercial.health
  commercial.health.pharmacy
  commercial.health.optician
  commercial.health.hearing_aids
  commercial.health.medical_supply
  commercial.health.herbalist
  commercial.chemist
  commercial.cosmetics
  commercial.toy
  commercial.pet
  commercial.pet.food
  commercial.smoking
  commercial.tobacco
  commercial.cannabis
  commercial.e_cigarette
  commercial.furniture
  commercial.furniture.kitchen
  commercial.furniture.lighting
  commercial.furniture.bed
  commercial.furniture.bathroom
  commercial.furniture.curtain
  commercial.interior_decoration
  commercial.houseware
  commercial.carpet
  commercial.trade
  commercial.weapon
  commercial.pyrotechnics
  commercial.erotic
  commercial.second_hand
  commercial.pawnbroker
  commercial.charity
  commercial.agrarian
  commercial.country_store
  commercial.energy
  commercial.glaziery
  commercial.gas
  commercial.wedding

  education
  education.school
  education.school.primary
  education.school.secondary
  education.university
  education.college
  education.library
  education.kindergarten
  education.music_school
  education.language_school
  education.driving_school
  education.dancing_school

  entertainment
  entertainment.culture
  entertainment.culture.theatre
  entertainment.culture.gallery
  entertainment.culture.arts_centre
  entertainment.culture.cultural_center
  entertainment.museum
  entertainment.cinema
  entertainment.casino
  entertainment.night_club
  entertainment.zoo
  entertainment.aquarium
  entertainment.theme_park
  entertainment.water_park
  entertainment.planetarium
  entertainment.escape_game
  entertainment.bowling_alley
  entertainment.amusement_arcade
  entertainment.miniature_golf
  entertainment.activity_park
  entertainment.miniature_park
  entertainment.laser_tag

  healthcare
  healthcare.hospital
  healthcare.clinic
  healthcare.clinic_or_praxis
  healthcare.dentist
  healthcare.pharmacy
  healthcare.veterinary
  healthcare.optometrist
  healthcare.physiotherapist
  healthcare.psychotherapist
  healthcare.laboratory
  healthcare.alternative
  healthcare.blood_donation

  heritage
  heritage.unesco

  leisure
  leisure.park
  leisure.playground
  leisure.garden
  leisure.dog_park
  leisure.picnic
  leisure.outdoor_seating
  leisure.firepit
  leisure.spa
  leisure.sauna
  leisure.hot_tub
  leisure.bird_hide
  leisure.fishing_spot
  leisure.marina
  leisure.slipway
  leisure.swimming_area
  leisure.bathing_place

  man_made
  man_made.bridge
  man_made.communications_tower
  man_made.lighthouse
  man_made.pier
  man_made.tower
  man_made.watermill
  man_made.windmill
  man_made.water_tower
  man_made.surveillance
  man_made.works
  man_made.beacon

  national_park

  natural
  natural.forest
  natural.water
  natural.water.lake
  natural.water.river
  natural.water.pond
  natural.water.stream
  natural.water.spring
  natural.water.hot_spring
  natural.water.waterfall
  natural.water.rapids
  natural.water.wetland
  natural.water.reservoir
  natural.water.canal
  natural.beach
  natural.cave_entrance
  natural.mountain_pass
  natural.peak
  natural.volcano
  natural.cliff
  natural.rock
  natural.sand
  natural.glacier
  natural.geyser
  natural.nature_reserve
  natural.protected_area

  office
  office.administrative
  office.government
  office.ngo
  office.insurance
  office.financial
  office.it
  office.newspaper
  office.estate_agent
  office.lawyer
  office.tax_advisor
  office.notary
  office.architect
  office.accountant
  office.company
  office.association
  office.travel_agent
  office.political_party
  office.diplomatic

  parking
  parking.cars
  parking.bicycles
  parking.motorcycles
  parking.underground
  parking.multi_storey

  pet
  pet.shop
  pet.veterinary
  pet.dog_park
  pet.shelter

  political

  power
  power.generator
  power.generator.wind
  power.generator.solar
  power.plant
  power.substation

  production
  production.factory
  production.brewery
  production.winery
  production.distillery
  production.cheese
  production.chocolate
  production.dairy
  production.bakery

  public_transport
  public_transport.train
  public_transport.train.station
  public_transport.train.halt
  public_transport.tram
  public_transport.bus
  public_transport.subway
  public_transport.ferry
  public_transport.funicular
  public_transport.airport
  public_transport.taxi

  rental
  rental.bicycle
  rental.car
  rental.ski
  rental.boat
  rental.scooter
  rental.canoe
  rental.kayak

  religion
  religion.place_of_worship
  religion.place_of_worship.christian
  religion.place_of_worship.church
  religion.place_of_worship.chapel
  religion.place_of_worship.cathedral
  religion.place_of_worship.basilica
  religion.place_of_worship.monastery
  religion.place_of_worship.muslim
  religion.place_of_worship.mosque
  religion.place_of_worship.jewish
  religion.place_of_worship.synagogue
  religion.place_of_worship.buddhist
  religion.place_of_worship.temple
  religion.place_of_worship.hindu
  religion.place_of_worship.shinto
  religion.place_of_worship.shrine
  religion.place_of_worship.taoist

  service
  service.financial
  service.financial.bank
  service.financial.atm
  service.financial.exchange
  service.post_office
  service.post_box
  service.police
  service.fire_station
  service.embassy
  service.townhall
  service.community_centre
  service.social_facility
  service.courthouse
  service.prison
  service.water
  service.telecom
  service.fuel
  service.vehicle
  service.vehicle.car_wash
  service.vehicle.car_parts
  service.vehicle.car_repair
  service.vehicle.tyre
  service.vehicle.charging_station
  service.vehicle.fuel
  service.beauty
  service.beauty.hairdresser
  service.beauty.spa
  service.beauty.cosmetics
  service.beauty.nails
  service.beauty.tattoo
  service.tailor
  service.dry_cleaning
  service.laundry
  service.locksmith
  service.photo
  service.printing
  service.copyshop
  service.key_cutting
  service.shoe_repair
  service.travel_agency
  service.estate_agent
  service.it
  service.recycling
  service.recycling.container
  service.recycling.bin
  service.recycling.centre
  service.waste
  service.waste.dump
  service.funeral
  service.storage
  service.coworking_space
  service.money_transfer
  service.pawnbroker
  service.massage
  service.baby_care
  service.internet_cafe

  ski
  ski.resort
  ski.lift

  sport
  sport.stadium
  sport.sports_centre
  sport.swimming_pool
  sport.ice_rink
  sport.fitness
  sport.golf
  sport.golf.course
  sport.golf.driving_range
  sport.golf.miniature_golf
  sport.tennis
  sport.basketball
  sport.soccer
  sport.football
  sport.baseball
  sport.volleyball
  sport.climbing
  sport.climbing.outdoor
  sport.climbing.indoor
  sport.equestrian
  sport.horse_racing
  sport.athletics
  sport.shooting_range
  sport.diving
  sport.diving.center
  sport.diving.site
  sport.water_sports
  sport.sailing
  sport.rowing
  sport.surfing
  sport.windsurfing
  sport.kitesurfing
  sport.skiing
  sport.snowboard
  sport.cycling
  sport.motorsport
  sport.karting
  sport.archery
  sport.bowling
  sport.boxing
  sport.martial_arts
  sport.yoga
  sport.skateboard
  sport.beachvolleyball
  sport.table_tennis
  sport.billiard
  sport.darts
  sport.cricket
  sport.rugby
  sport.hockey
  sport.badminton
  sport.squash
  sport.curling
  sport.fencing
  sport.handball
  sport.gymnastics

  tourism
  tourism.attraction
  tourism.sights
  tourism.sights.memorial
  tourism.sights.tower
  tourism.sights.windmill
  tourism.sights.watermill
  tourism.sights.fort
  tourism.sights.castle
  tourism.sights.palace
  tourism.sights.manor
  tourism.sights.ruines
  tourism.sights.archaeological_site
  tourism.sights.city_gate
  tourism.sights.battlefield
  tourism.sights.boundary_stone
  tourism.sights.monastery
  tourism.sights.wayside_cross
  tourism.sights.wayside_shrine
  tourism.sights.statue
  tourism.sights.pillory
  tourism.sights.aircraft
  tourism.sights.locomotive
  tourism.sights.ship
  tourism.sights.tank
  tourism.sights.cannon
  tourism.information
  tourism.information.office
  tourism.information.visitor_centre
  tourism.information.terminal
  tourism.information.board
  tourism.information.map
  tourism.information.guidepost
  tourism.information.route_marker
  tourism.viewpoint
  tourism.artwork
  tourism.artwork.sculpture
  tourism.artwork.mural
  tourism.artwork.installation
  tourism.artwork.painting
  tourism.artwork.street_art
  tourism.alpine_hut
  tourism.picnic_site
  tourism.camp_site
  tourism.caravan_site
  tourism.wilderness_hut
].freeze
