# frozen_string_literal: true

# Changes ai_generated default from true to false
#
# Previously, all content was assumed AI-generated by default.
# Now, content is assumed human-created by default, and AI services
# must explicitly set ai_generated: true when creating content.
#
# Existing records are NOT changed - they keep ai_generated: true
# since they were created when that was the default.
class ChangeAiGeneratedDefaultToFalse < ActiveRecord::Migration[8.1]
  def up
    # Change default to false for all tables with ai_generated column
    change_column_default :locations, :ai_generated, from: true, to: false
    change_column_default :experiences, :ai_generated, from: true, to: false
    change_column_default :plans, :ai_generated, from: true, to: false
    change_column_default :browses, :ai_generated, from: true, to: false
  end

  def down
    # Revert to original default of true
    change_column_default :locations, :ai_generated, from: false, to: true
    change_column_default :experiences, :ai_generated, from: false, to: true
    change_column_default :plans, :ai_generated, from: false, to: true
    change_column_default :browses, :ai_generated, from: false, to: true
  end
end
